Support for deletion of multiple files
pterodactyl/Daemon pull request #44
Opened 2017-07-10 00:53 UTC by OrangeJuiced

This pull request contains the code that supports deletion of multiple files.

2017-07-10 01:14 UTC, DaneEveritt requested changes
Overall looks pretty good, I think this might be better suited to work more like `copy` or other functions that accept an array of files to work with.

If we do that, we need to change the API endpoint, which is something I am okay with so long as the panel is also updated.

2017-07-10 01:14 UTC, DaneEveritt commented on src/controllers/fs.js
> +        var res = path.split(",")
This should use lodash's `_.split` function over native.

2017-07-10 01:14 UTC, DaneEveritt commented on src/controllers/fs.js
> +        var i;
`var` is not used in this project, please use `let` here, and `const` where needed elsewhere.

2017-07-10 01:14 UTC, DaneEveritt commented on src/controllers/fs.js
> +        for (i = 0; i < res.length; i++) {
This should use `Async.each` operations ideally.

2017-07-11 00:53 UTC, OrangeJuiced commented
I have changed the endpoint and rewritten the delete function to more closely resemble `copy`.

2017-07-20 23:11 UTC, DaneEveritt commented on src/http/routes.js
> -RestServer.del(/^\/server\/file\/f\/(.+)/, (req, res, next) => {
This is a breaking change. Please revert it or confirm that no other locations in the panel hit this endpoint.

2017-07-22 14:19 UTC, OrangeJuiced commented on src/http/routes.js
> -RestServer.del(/^\/server\/file\/f\/(.+)/, (req, res, next) => {
I have double checked. I can't find anything else that uses that endpoint.

2017-07-22 16:52 UTC, DaneEveritt approved these changes

2017-07-22 16:52 UTC, merged